import type { Metadata } from "next";
import "../styles/globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={frFR}>
      <html lang="fr">
        <body
          className={cn(
            "min-h-screen max-w-7xl mx-auto flex flex-col items-center bg-background font-sans antialiased"
          )}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">Chargement...</div>
          </ClerkLoading>
          <ClerkLoaded>
            <Header />
            {children}
            <Footer />
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
